//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProgramlamaProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anasayfas
    {
        public int id { get; set; }
        public string postResim { get; set; }
        public string postBaslik { get; set; }
        public string postTarih { get; set; }
        public string postIcerik { get; set; }
    }
}
