//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProgramlamaProje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebProgramlamaProjeDBEntities : DbContext
    {
        public WebProgramlamaProjeDBEntities()
            : base("name=WebProgramlamaProjeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Anasayfas> Anasayfas { get; set; }
        public virtual DbSet<Kullanicis> Kullanicis { get; set; }
        public virtual DbSet<Yorums> Yorums { get; set; }
    }
}
