//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProgramlamaProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorums
    {
        public int YorumId { get; set; }
        public string Mesaj { get; set; }
        public int PostID { get; set; }
        public int UserID { get; set; }
    }
}
